### ISSUE TITLE
should "github.com/mitchellh/go-homedir" be vendored?

### ISSUE THREAD

**Issue by a86c6f7964** [hashicorp/go-rootcerts#1]
https://github.com/hashicorp/go-rootcerts/blob/6bb64b370b90e7ef1fa532be9e591a81c3493e00/rootcerts_darwin.go#L8

I am having trouble compiling nomad

**Comment by themasterchef** [comment]
This undeclared dependency also breaks cross-compilation of atlas-upload-cli for OSX.

**Comment by jefferai** [comment]
Generally speaking you vendor in programs, not libraries. It's `atlas-upload-cli` that should be vendoring both items. That's the right place to file a bug against this, which I've done above.

**Comment by themasterchef** [comment]
Thanks :) I'm new to the Go world so didn't know that
